services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: joaovitor98/bangalo-app
    container_name: app
    tty: true
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    networks:
      - bangalo
    environment:
      - APPLICATION_PORT=3000
      - NODE_ENV=development
      - MARIADB_USER=application
      - MARIADB_DATABASE=bangalo
      - MARIADB_ROOT_PASSWORD=da21zg53
      - MARIADB_PASSWORD=da21zg52
      - MARIADB_PORT=3306
      - MARIADB_DIALECT=mariadb
      - MARIADB_HOST=database
      - STORAGE_SERVICE=http://storage:4000/v1
    depends_on:
      - database
      - storage
  database:
    image: mariadb:10.5
    container_name: database
    command: --innodb-use-native-aio=0
    ports:
      - 3306:3306
    volumes:
      - ./cache/database:/var/lib/mysql
    networks:
      - bangalo
    environment:
      - MARIADB_USER=application
      - MARIADB_DATABASE=bangalo
      - MARIADB_PASSWORD=da21zg52
      - MARIADB_ROOT_PASSWORD=da21zg53
    tty: true
    restart: always
  storage:
    build:
      context: ./plugins/storage
      dockerfile: Dockerfile
    image: joaovitor98/storage-app
    container_name: storage
    tty: true
    restart: always
    environment:
      - APPLICATION_STORAGE_PORT=4000
      - APPLICATION_STORAGE_ACCESS=http://localhost:3000
    volumes:
      - ./plugins/storage:/usr/src/storage
    ports:
      - 4000:4000
    networks:
      - bangalo
  nginx:
    build:
      context: ./src/nginx/
      dockerfile: Dockerfile
    image: joaovitor98/nginx-app
    container_name: nginx
    ports:
      - 8080:80
    networks:
      - bangalo
    tty: true
    restart: always
    depends_on:
      - app

networks:
  bangalo:
    driver: bridge
